telegram:
  token_env: TELEGRAM_TOKEN
  chat_id_env: TELEGRAM_CHAT_ID
searches:
- name: warszawa-rent
  url: https://www.otodom.pl/pl/wyniki/wynajem/mieszkanie/mazowieckie/warszawa/warszawa/warszawa?limit=36
  text_must_contain:
  - balkon
  - taras
  - ogród
  text_must_not_contain:
  - kawalerka
  - parter
