telegram:
  token_env: TELEGRAM_TOKEN
  chat_id_env: TELEGRAM_CHAT_ID
searches:
- name: warszawa-rent
  url: https://www.otodom.pl/pl/wyniki/wynajem/mieszkanie/mazowieckie/warszawa/warszawa/warszawa?limit=36&locations=%5Bmazowieckie%2Fwarszawa%2Fwarszawa%2Fwarszawa%2Fbielany%5D&priceMax=3500&roomsNumber=%5BTWO%5D
  text_must_contain:
  - balkon
  - taras
  - ogród
  text_must_not_contain:
  - kawalerka
  - parter
